-- One-time migration: dynamic user-defined ("custom") fields.
-- Run once in Supabase -> SQL Editor.
--
-- 1) A `custom` JSON map on each record type holds the values.
-- 2) A `field_defs` table describes the fields the UI should render
--    (per entity: property / lease / transaction).

alter table public.properties   add column if not exists custom jsonb not null default '{}'::jsonb;
alter table public.leases        add column if not exists custom jsonb not null default '{}'::jsonb;
alter table public.transactions  add column if not exists custom jsonb not null default '{}'::jsonb;

create table if not exists public.field_defs (
  id          bigint generated by default as identity primary key,
  entity      text not null check (entity in ('property', 'lease', 'transaction')),
  field_key   text not null,
  label       text not null,
  field_type  text not null default 'text'
              check (field_type in ('text', 'number', 'date', 'select', 'checkbox')),
  options     text,
  sort_order  integer default 0,
  created_at  timestamptz not null default now(),
  unique (entity, field_key)
);

-- Match the RLS posture used by the rest of the schema: any authenticated user
-- of this project can read/write. (Adjust if you later add per-user scoping.)
alter table public.field_defs enable row level security;

drop policy if exists field_defs_all on public.field_defs;
create policy field_defs_all on public.field_defs
  for all to authenticated using (true) with check (true);

notify pgrst, 'reload schema';
